spring.application.name=portfolio-backend
server.port=8080
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/portfolio}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Shubham@123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:shubhamkalwar198@gmail.com}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
springdoc.swagger-ui.path=/swagger-ui.html
app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:4200}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.mail.enabled=false

